export enum VendaOrigem {
  GOIANIA = 'GOIANIA',
  INHUMAS = 'INHUMAS',
  UBERABA = 'UBERABA',
  NEROPOLIS = 'NEROPOLIS',
  RIBEIRAO_PRETO = 'RIBEIRAO_PRETO',
  OUTRO = 'OUTRO',
}

export enum VendaStatus {
  REGISTRADO = 'REGISTRADO',
  CANCELADO = 'CANCELADO',
  PAGO = 'PAGO',
  PAGO_PARCIAL = 'PAGO_PARCIAL',
  FECHADO = 'FECHADO',
}

export enum TipoAtualizacao {
  FORMULA_CERTA_AGENTE = 'FORMULA_CERTA_AGENTE',
  VALOR_CLIENTE = 'VALOR_CLIENTE',
}
